"""Render a README figure from the CLI's synthetic demo; never open a camera.

Install .[analysis], then run the two commands documented below the README image.
The source image and channels.json are generated by flyvisionbridge.cli --demo.
"""
import argparse
from collections import Counter
import json
from pathlib import Path

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('demo', type=Path, help='Output directory of --demo --eyes both')
    parser.add_argument('--output', type=Path, default=Path('docs/assets/synthetic-sampling.png'))
    args = parser.parse_args()
    result = json.loads((args.demo / 'channels.json').read_text(encoding='utf-8'))
    if result.get('clock_domain') != 'SYNTHETIC' or result.get('source') != 'synthetic demonstration':
        parser.error('Only synthetic CLI output is accepted for the public README figure')
    rgb = np.asarray(Image.open(args.demo / 'rgb.png').convert('RGB'))
    expected = np.full((480, 640, 3), 220, np.uint8)
    expected[150:330, 260:380] = 30
    if not np.array_equal(rgb, expected):
        parser.error('Image differs from the known synthetic CLI stimulus')
    rows = result['channels']
    if {r['eye'] for r in rows} != {'L', 'R'}:
        parser.error('Generate the demo with --eyes both')
    counts = Counter(r['rgb_status'] for r in rows)
    observed = [r for r in rows if r['rgb_status'] == 'OBSERVED']
    eye_counts = Counter(r['eye'] for r in observed)
    plt.rcParams.update({'font.family': 'DejaVu Sans', 'font.size': 13})
    fig, axes = plt.subplots(1, 2, figsize=(12, 6.5), dpi=140)
    fig.patch.set_facecolor('#f6f8fb')
    fig.subplots_adjust(left=.05, right=.95, top=.79, bottom=.22, wspace=.14)
    fig.text(.05, .94, 'Camera pixels to fruit-fly visual inputs', fontsize=23, weight='bold', color='#13283d')
    fig.text(.05, .883, 'Synthetic RGB image + published L2 directions | actual bridge output', color='#42576b')
    for ax in axes:
        ax.imshow(rgb)
        ax.set_xlim(-.5, rgb.shape[1] - .5)
        ax.set_ylim(rgb.shape[0] - .5, -.5)
        ax.set_xticks([])
        ax.set_yticks([])
        for spine in ax.spines.values():
            spine.set_edgecolor('#c9d3dc')
    axes[0].set_title('1. Synthetic input', loc='left', pad=12, weight='bold')
    axes[1].set_title('2. Observed left / right L2 positions', loc='left', pad=12, weight='bold')
    for eye, color in [('L', '#0076c8'), ('R', '#dd6600')]:
        uv = np.array([r['pixel_uv'] for r in observed if r['eye'] == eye])
        if len(uv):
            axes[1].scatter(uv[:, 0], uv[:, 1], s=19, color=color, linewidths=.4,
                            edgecolors='white', label=f'{eye}: {eye_counts[eye]} observed')
    axes[1].legend(loc='upper center', bbox_to_anchor=(.5, -.035), ncols=2, frameon=False,
                   fontsize=11, handletextpad=.3, columnspacing=1)
    fig.text(.05, .16, f"{len(observed)} observed / {len(rows):,} targets", fontsize=15, weight='bold', color='#13283d')
    fig.text(.05, .112, f"{counts['OUTSIDE_CAMERA_FOV']:,} outside the camera view; {counts['MISSING_DIRECTION']} without a mapped direction. Both stay null.", fontsize=11, color='#42576b')
    fig.text(.05, .062, 'Assumed demo geometry: 640 x 480, fx = fy = 600 px. RGB samples, not neural spikes.', fontsize=11, color='#42576b')
    fig.text(.05, .022, 'Directions: Arthur Zhao / Reiser Lab (CC BY-SA 4.0). Full source terms: THIRD_PARTY_NOTICES.md.', fontsize=9, color='#60758a')
    args.output.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(args.output, facecolor=fig.get_facecolor())
    plt.close(fig)
    print(json.dumps({'figure': str(args.output), 'targets': len(rows), 'statuses': dict(counts), 'observed_by_eye': dict(eye_counts)}))


if __name__ == '__main__':
    main()
